import { NextRequest, NextResponse } from "next/server";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

const tariffs = [
  { id: "copart-AZ-Tucson", auction: "copart", state: "AZ", city: "Tucson", price: 2435 },
  { id: "iaai-AZ-Tucson", auction: "iaai", state: "AZ", city: "Tucson", price: 2435 },
  { id: "copart-AZ-Phoenix", auction: "copart", state: "AZ", city: "Phoenix", price: 2375 },
  { id: "iaai-AZ-Phoenix", auction: "iaai", state: "AZ", city: "Phoenix", price: 2375 },
  { id: "copart-AZ-Phoenix North", auction: "copart", state: "AZ", city: "Phoenix North", price: 2375 },
  { id: "copart-MT-Helena", auction: "copart", state: "MT", city: "Helena", price: 2935 },
  { id: "copart-MT-Billings", auction: "copart", state: "MT", city: "Billings", price: 2835 },
  { id: "iaai-MT-Billings", auction: "iaai", state: "MT", city: "Billings", price: 2835 },
  { id: "iaai-MT-Missoula", auction: "iaai", state: "MT", city: "Missoula", price: 2885 },
  { id: "copart-WI-Appleton", auction: "copart", state: "WI", city: "Appleton", price: 2085 },
  { id: "iaai-WI-Appleton", auction: "iaai", state: "WI", city: "Appleton", price: 2085 },
  { id: "copart-WI-Madison South", auction: "copart", state: "WI", city: "Madison South", price: 2085 },
  { id: "copart-WI-Milwaukee North", auction: "copart", state: "WI", city: "Milwaukee North", price: 2085 },
  { id: "copart-WI-Milwaukee South", auction: "copart", state: "WI", city: "Milwaukee South", price: 2085 },
  { id: "iaai-WI-Milwaukee", auction: "iaai", state: "WI", city: "Milwaukee", price: 2085 },
  { id: "iaai-WI-Portage", auction: "iaai", state: "WI", city: "Portage", price: 2085 },
  { id: "copart-FL-Orlando North", auction: "copart", state: "FL", city: "Orlando North", price: 1685 },
  { id: "copart-FL-Miami Central", auction: "copart", state: "FL", city: "Miami Central", price: 1685 },
  { id: "copart-FL-West Palm Beach", auction: "copart", state: "FL", city: "West Palm Beach", price: 1685 },
  { id: "iaai-FL-West Palm Beach", auction: "iaai", state: "FL", city: "West Palm Beach", price: 1685 },
  { id: "copart-FL-Tampa South", auction: "copart", state: "FL", city: "Tampa South", price: 1685 },
  { id: "copart-FL-Miami North", auction: "copart", state: "FL", city: "Miami North", price: 1685 },
  { id: "iaai-FL-Miami North", auction: "iaai", state: "FL", city: "Miami North", price: 1685 },
  { id: "copart-FL-Orlando South", auction: "copart", state: "FL", city: "Orlando South", price: 1685 },
  { id: "iaai-FL-Orlando South", auction: "iaai", state: "FL", city: "Orlando South", price: 1685 },
  { id: "copart-FL-Jacksonville North", auction: "copart", state: "FL", city: "Jacksonville North", price: 1685 },
  { id: "iaai-FL-Jacksonville", auction: "iaai", state: "FL", city: "Jacksonville", price: 1685 },
  { id: "copart-FL-Ocala", auction: "copart", state: "FL", city: "Ocala", price: 1685 },
  { id: "copart-FL-Miami South", auction: "copart", state: "FL", city: "Miami South", price: 1685 },
  { id: "copart-FL-Ft.Pierce", auction: "copart", state: "FL", city: "Ft.Pierce", price: 1685 },
  { id: "iaai-FL-Ft.Pierce", auction: "iaai", state: "FL", city: "Ft.Pierce", price: 1685 },
  { id: "copart-FL-Punta Gorda", auction: "copart", state: "FL", city: "Punta Gorda", price: 1835 },
  { id: "copart-FL-Tampa North", auction: "copart", state: "FL", city: "Tampa North", price: 1685 },
  { id: "iaai-FL-Tampa North", auction: "iaai", state: "FL", city: "Tampa North", price: 1685 },
  { id: "iaai-FL-Tampa", auction: "iaai", state: "FL", city: "Tampa", price: 1685 },
  { id: "copart-FL-Orlando", auction: "copart", state: "FL", city: "Orlando", price: 1685 },
  { id: "iaai-FL-Pensacola", auction: "iaai", state: "FL", city: "Pensacola", price: 1735 },
  { id: "iaai-FL-Clearwater", auction: "iaai", state: "FL", city: "Clearwater", price: 1685 },
  { id: "iaai-FL-Fort Myers", auction: "iaai", state: "FL", city: "Fort Myers", price: 1685 },
  { id: "copart-NY-Buffalo", auction: "copart", state: "NY", city: "Buffalo", price: 1855 },
  { id: "iaai-NY-Buffalo", auction: "iaai", state: "NY", city: "Buffalo", price: 1835 },
  { id: "copart-NY-Newburgh", auction: "copart", state: "NY", city: "Newburgh", price: 1645 },
  { id: "iaai-NY-Newburgh", auction: "iaai", state: "NY", city: "Newburgh", price: 1635 },
  { id: "copart-NY-Rochester", auction: "copart", state: "NY", city: "Rochester", price: 1775 },
  { id: "iaai-NY-Rochester", auction: "iaai", state: "NY", city: "Rochester", price: 1760 },
  { id: "copart-NY-Syracuse", auction: "copart", state: "NY", city: "Syracuse", price: 1695 },
  { id: "iaai-NY-Syracuse", auction: "iaai", state: "NY", city: "Syracuse", price: 1835 },
  { id: "copart-NY-Long Island", auction: "copart", state: "NY", city: "Long Island", price: 1645 },
  { id: "iaai-NY-Long Island", auction: "iaai", state: "NY", city: "Long Island", price: 1635 },
  { id: "copart-NY-Albany", auction: "copart", state: "NY", city: "Albany", price: 1675 },
  { id: "iaai-NY-Albany", auction: "iaai", state: "NY", city: "Albany", price: 1660 },
  { id: "iaai-NY-Staten Island", auction: "iaai", state: "NY", city: "Staten Island", price: 1635 },
  { id: "iaai-NY-Monticello", auction: "iaai", state: "NY", city: "Monticello", price: 1685 },
  { id: "copart-VA-Richmond East", auction: "copart", state: "VA", city: "Richmond East", price: 1785 },
  { id: "copart-VA-Fredericksburg", auction: "copart", state: "VA", city: "Fredericksburg", price: 1785 },
  { id: "copart-VA-Richmond", auction: "copart", state: "VA", city: "Richmond", price: 1735 },
  { id: "iaai-VA-Richmond", auction: "iaai", state: "VA", city: "Richmond", price: 1735 },
  { id: "copart-VA-Hampton", auction: "copart", state: "VA", city: "Hampton", price: 1785 },
  { id: "copart-VA-Danville", auction: "copart", state: "VA", city: "Danville", price: 1835 },
  { id: "iaai-VA-Suffolk", auction: "iaai", state: "VA", city: "Suffolk", price: 1810 },
  { id: "iaai-VA-Tidawater", auction: "iaai", state: "VA", city: "Tidawater", price: 1745 },
  { id: "iaai-VA-Pulaski", auction: "iaai", state: "VA", city: "Pulaski", price: 1835 },
  { id: "iaai-VA-Northen Virginia", auction: "iaai", state: "VA", city: "Northen Virginia", price: 1685 },
  { id: "iaai-VA-Culpeper", auction: "iaai", state: "VA", city: "Culpeper", price: 1785 },
  { id: "iaai-VA-Roanoke", auction: "iaai", state: "VA", city: "Roanoke", price: 1785 },
  { id: "copart-ID-Boise", auction: "copart", state: "ID", city: "Boise", price: 2735 },
  { id: "iaai-ID-Boise", auction: "iaai", state: "ID", city: "Boise", price: 2735 },
  { id: "copart-CO-Denver", auction: "copart", state: "CO", city: "Denver", price: 2235 },
  { id: "copart-CO-Denver South", auction: "copart", state: "CO", city: "Denver South", price: 2235 },
  { id: "copart-CO-Colorado Springs", auction: "copart", state: "CO", city: "Colorado Springs", price: 2225 },
  { id: "iaai-CO-Colorado Springs", auction: "iaai", state: "CO", city: "Colorado Springs", price: 2235 },
  { id: "copart-CO-Denver Central", auction: "copart", state: "CO", city: "Denver Central", price: 2235 },
  { id: "iaai-CO-Westrern Colorado", auction: "iaai", state: "CO", city: "Westrern Colorado", price: 3085 },
  { id: "iaai-CO-Denver East", auction: "iaai", state: "CO", city: "Denver East", price: 2185 },
  { id: "copart-IA-Des Moines", auction: "copart", state: "IA", city: "Des Moines", price: 1985 },
  { id: "iaai-IA-Des Moines", auction: "iaai", state: "IA", city: "Des Moines", price: 1985 },
  { id: "copart-IA-Devenport", auction: "copart", state: "IA", city: "Devenport", price: 1985 },
  { id: "iaai-IA-Devenport", auction: "iaai", state: "IA", city: "Devenport", price: 1960 },
  { id: "copart-IA-Cedar Rapids", auction: "copart", state: "IA", city: "Cedar Rapids", price: 1985 },
  { id: "copart-TX-Waco", auction: "copart", state: "TX", city: "Waco", price: 1835 },
  { id: "copart-TX-Andrews", auction: "copart", state: "TX", city: "Andrews", price: 2060 },
  { id: "copart-TX-San Antonio", auction: "copart", state: "TX", city: "San Antonio", price: 1885 },
  { id: "copart-TX-Dallas South", auction: "copart", state: "TX", city: "Dallas South", price: 1835 },
  { id: "copart-TX-Carshed Toys Dallas", auction: "copart", state: "TX", city: "Carshed Toys Dallas", price: 1805 },
  { id: "copart-TX-Austin", auction: "copart", state: "TX", city: "Austin", price: 1835 },
  { id: "iaai-TX-Austin", auction: "iaai", state: "TX", city: "Austin", price: 1845 },
  { id: "copart-TX-Mcallen", auction: "copart", state: "TX", city: "Mcallen", price: 1905 },
  { id: "iaai-TX-Mcallen", auction: "iaai", state: "TX", city: "Mcallen", price: 1905 },
  { id: "copart-TX-Lufkin", auction: "copart", state: "TX", city: "Lufkin", price: 1835 },
  { id: "copart-TX-Longview", auction: "copart", state: "TX", city: "Longview", price: 1845 },
  { id: "iaai-TX-Longview", auction: "iaai", state: "TX", city: "Longview", price: 1875 },
  { id: "copart-TX-Houston", auction: "copart", state: "TX", city: "Houston", price: 1735 },
  { id: "iaai-TX-Houston", auction: "iaai", state: "TX", city: "Houston", price: 1785 },
  { id: "copart-TX-Ft.Worth", auction: "copart", state: "TX", city: "Ft.Worth", price: 1875 },
  { id: "copart-TX-Dallas", auction: "copart", state: "TX", city: "Dallas", price: 1835 },
  { id: "iaai-TX-Dallas", auction: "iaai", state: "TX", city: "Dallas", price: 1835 },
  { id: "copart-TX-Corpus Christi", auction: "copart", state: "TX", city: "Corpus Christi", price: 1845 },
  { id: "iaai-TX-Corpus Christi", auction: "iaai", state: "TX", city: "Corpus Christi", price: 1845 },
  { id: "copart-TX-El Paso", auction: "copart", state: "TX", city: "El Paso", price: 2060 },
  { id: "iaai-TX-El Paso", auction: "iaai", state: "TX", city: "El Paso", price: 2085 },
  { id: "copart-TX-Amarillo", auction: "copart", state: "TX", city: "Amarillo", price: 2085 },
  { id: "iaai-TX-Amarillo", auction: "iaai", state: "TX", city: "Amarillo", price: 2085 },
  { id: "copart-TX-Abiline", auction: "copart", state: "TX", city: "Abiline", price: 1935 },
  { id: "iaai-TX-Abiline", auction: "iaai", state: "TX", city: "Abiline", price: 1935 },
  { id: "copart-TX-Houston East", auction: "copart", state: "TX", city: "Houston East", price: 1735 },
  { id: "copart-TX-North Austin", auction: "copart", state: "TX", city: "North Austin", price: 1935 },
  { id: "iaai-TX-North Austin", auction: "iaai", state: "TX", city: "North Austin", price: 1935 },
  { id: "iaai-TX-Houston South", auction: "iaai", state: "TX", city: "Houston South", price: 1785 },
  { id: "iaai-TX-Fort Worth North", auction: "iaai", state: "TX", city: "Fort Worth North", price: 1875 },
  { id: "iaai-TX-Permian Basin", auction: "iaai", state: "TX", city: "Permian Basin", price: 1935 },
  { id: "iaai-TX-Houston North", auction: "iaai", state: "TX", city: "Houston North", price: 1785 },
  { id: "iaai-TX-San Antonio South", auction: "iaai", state: "TX", city: "San Antonio South", price: 1885 },
  { id: "iaai-TX-Lubbock", auction: "iaai", state: "TX", city: "Lubbock", price: 2035 },
  { id: "iaai-TX-Dallas Ft.Worth", auction: "iaai", state: "TX", city: "Dallas Ft.Worth", price: 1815 },
  { id: "copart-OH-Dayton", auction: "copart", state: "OH", city: "Dayton", price: 1835 },
  { id: "iaai-OH-Dayton", auction: "iaai", state: "OH", city: "Dayton", price: 1835 },
  { id: "copart-OH-Cleveland East", auction: "copart", state: "OH", city: "Cleveland East", price: 1835 },
  { id: "copart-OH-Columbus", auction: "copart", state: "OH", city: "Columbus", price: 1835 },
  { id: "iaai-OH-Columbus", auction: "iaai", state: "OH", city: "Columbus", price: 1800 },
  { id: "copart-OH-Cleveland West", auction: "copart", state: "OH", city: "Cleveland West", price: 1835 },
  { id: "iaai-OH-Cincinnati -South", auction: "iaai", state: "OH", city: "Cincinnati -South", price: 1860 },
  { id: "iaai-OH-Cincinnati", auction: "iaai", state: "OH", city: "Cincinnati", price: 1810 },
  { id: "iaai-OH-Akron Canton", auction: "iaai", state: "OH", city: "Akron Canton", price: 1815 },
  { id: "iaai-OH-Cleveland", auction: "iaai", state: "OH", city: "Cleveland", price: 1810 },
  { id: "copart-MN-Minneapolis", auction: "copart", state: "MN", city: "Minneapolis", price: 1975 },
  { id: "copart-MN-St.Cloud", auction: "copart", state: "MN", city: "St.Cloud", price: 1960 },
  { id: "iaai-MN-St.Cloud", auction: "iaai", state: "MN", city: "St.Cloud", price: 2035 },
  { id: "copart-MN-Minneapolis North", auction: "copart", state: "MN", city: "Minneapolis North", price: 1985 },
  { id: "iaai-MN-Minneapolis st.paul", auction: "iaai", state: "MN", city: "Minneapolis st.paul", price: 1935 },
  { id: "copart-MN-Minneapolis South", auction: "copart", state: "MN", city: "Minneapolis South", price: 1985 },
  { id: "copart-NH-Candia", auction: "copart", state: "NH", city: "Candia", price: 1785 },
  { id: "iaai-NH-Manchester", auction: "iaai", state: "NH", city: "Manchester", price: 1735 },
  { id: "copart-WA-Pasco", auction: "copart", state: "WA", city: "Pasco", price: 2585 },
  { id: "copart-WA-Graham", auction: "copart", state: "WA", city: "Graham", price: 2460 },
  { id: "copart-WA-North Seattle", auction: "copart", state: "WA", city: "North Seattle", price: 2585 },
  { id: "copart-WA-Spokane", auction: "copart", state: "WA", city: "Spokane", price: 2685 },
  { id: "iaai-WA-Spokane", auction: "iaai", state: "WA", city: "Spokane", price: 2685 },
  { id: "copart-WA-Spanaway", auction: "copart", state: "WA", city: "Spanaway", price: 2585 },
  { id: "iaai-WA-Seattle", auction: "iaai", state: "WA", city: "Seattle", price: 2485 },
  { id: "copart-CT-Hartford Springfield", auction: "copart", state: "CT", city: "Hartford Springfield", price: 1710 },
  { id: "copart-CT-Hartford", auction: "copart", state: "CT", city: "Hartford", price: 1635 },
  { id: "iaai-CT-Hartford", auction: "iaai", state: "CT", city: "Hartford", price: 1635 },
  { id: "copart-AL-Tanner", auction: "copart", state: "AL", city: "Tanner", price: 1760 },
  { id: "copart-AL-Montgomery", auction: "copart", state: "AL", city: "Montgomery", price: 1760 },
  { id: "copart-AL-Birmingham", auction: "copart", state: "AL", city: "Birmingham", price: 1760 },
  { id: "iaai-AL-Birmingham", auction: "iaai", state: "AL", city: "Birmingham", price: 1765 },
  { id: "copart-AL-Mobile", auction: "copart", state: "AL", city: "Mobile", price: 1745 },
  { id: "iaai-AL-Mobile", auction: "iaai", state: "AL", city: "Mobile", price: 1805 },
  { id: "copart-AL-Dothan", auction: "copart", state: "AL", city: "Dothan", price: 1725 },
  { id: "iaai-AL-Dothan", auction: "iaai", state: "AL", city: "Dothan", price: 1735 },
  { id: "copart-AL-Mobile south", auction: "copart", state: "AL", city: "Mobile south", price: 1735 },
  { id: "copart-AL-Cusseta", auction: "copart", state: "AL", city: "Cusseta", price: 1885 },
  { id: "iaai-AL-Huntsvile", auction: "iaai", state: "AL", city: "Huntsvile", price: 1745 },
  { id: "copart-PA-Philadelphia East", auction: "copart", state: "PA", city: "Philadelphia East", price: 1615 },
  { id: "copart-PA-York Haven", auction: "copart", state: "PA", city: "York Haven", price: 1725 },
  { id: "copart-PA-Pittsburgh South", auction: "copart", state: "PA", city: "Pittsburgh South", price: 1795 },
  { id: "copart-PA-Philadelphia", auction: "copart", state: "PA", city: "Philadelphia", price: 1615 },
  { id: "iaai-PA-Philadelphia", auction: "iaai", state: "PA", city: "Philadelphia", price: 1625 },
  { id: "copart-PA-Harissburg", auction: "copart", state: "PA", city: "Harissburg", price: 1725 },
  { id: "copart-PA-Pittsburgh North", auction: "copart", state: "PA", city: "Pittsburgh North", price: 1795 },
  { id: "iaai-PA-Pittsburgh North", auction: "iaai", state: "PA", city: "Pittsburgh North", price: 1795 },
  { id: "copart-PA-Altoona", auction: "copart", state: "PA", city: "Altoona", price: 1795 },
  { id: "iaai-PA-Altoona", auction: "iaai", state: "PA", city: "Altoona", price: 1795 },
  { id: "copart-PA-Scranton", auction: "copart", state: "PA", city: "Scranton", price: 1645 },
  { id: "iaai-PA-Scranton", auction: "iaai", state: "PA", city: "Scranton", price: 1645 },
  { id: "copart-PA-Chambersburg", auction: "copart", state: "PA", city: "Chambersburg", price: 1775 },
  { id: "copart-PA-Pittsburgh West", auction: "copart", state: "PA", city: "Pittsburgh West", price: 1795 },
  { id: "copart-PA-Philadelphia East -sublot", auction: "copart", state: "PA", city: "Philadelphia East -sublot", price: 1615 },
  { id: "iaai-PA-York Springs", auction: "iaai", state: "PA", city: "York Springs", price: 1695 },
  { id: "iaai-PA-Erie", auction: "iaai", state: "PA", city: "Erie", price: 1875 },
  { id: "iaai-PA-Bridgeport", auction: "iaai", state: "PA", city: "Bridgeport", price: 1645 },
  { id: "iaai-PA-Pittsburgh", auction: "iaai", state: "PA", city: "Pittsburgh", price: 1795 },
  { id: "copart-UT-Ogden", auction: "copart", state: "UT", city: "Ogden", price: 2485 },
  { id: "copart-UT-Salt Lake City", auction: "copart", state: "UT", city: "Salt Lake City", price: 2535 },
  { id: "iaai-UT-Salt Lake City", auction: "iaai", state: "UT", city: "Salt Lake City", price: 2535 },
  { id: "copart-UT-Provo", auction: "copart", state: "UT", city: "Provo", price: 2535 },
  { id: "copart-LA-Shreveport", auction: "copart", state: "LA", city: "Shreveport", price: 1905 },
  { id: "iaai-LA-Shreveport", auction: "iaai", state: "LA", city: "Shreveport", price: 1905 },
  { id: "copart-LA-New Orleans", auction: "copart", state: "LA", city: "New Orleans", price: 1925 },
  { id: "copart-LA-Baton Rouge", auction: "copart", state: "LA", city: "Baton Rouge", price: 1985 },
  { id: "iaai-LA-Baton Rouge", auction: "iaai", state: "LA", city: "Baton Rouge", price: 1905 },
  { id: "copart-LA-Vinton", auction: "copart", state: "LA", city: "Vinton", price: 2035 },
  { id: "iaai-LA-New Orleans East", auction: "iaai", state: "LA", city: "New Orleans East", price: 1955 },
  { id: "iaai-LA-Lafayette", auction: "iaai", state: "LA", city: "Lafayette", price: 1915 },
  { id: "copart-MS-Jackson", auction: "copart", state: "MS", city: "Jackson", price: 1965 },
  { id: "copart-MS-Grenada", auction: "copart", state: "MS", city: "Grenada", price: 2055 },
  { id: "iaai-MS-Grenada", auction: "iaai", state: "MS", city: "Grenada", price: 2055 },
  { id: "iaai-MS-Gulf Coast", auction: "iaai", state: "MS", city: "Gulf Coast", price: 1935 },
  { id: "copart-NJ-Trenton", auction: "copart", state: "NJ", city: "Trenton", price: 1545 },
  { id: "copart-NJ-Somerville", auction: "copart", state: "NJ", city: "Somerville", price: 1545 },
  { id: "copart-NJ-Glassboro East", auction: "copart", state: "NJ", city: "Glassboro East", price: 1610 },
  { id: "copart-NJ-Glassboro West", auction: "copart", state: "NJ", city: "Glassboro West", price: 1610 },
  { id: "iaai-NJ-Southern New Jersey", auction: "iaai", state: "NJ", city: "Southern New Jersey", price: 1585 },
  { id: "iaai-NJ-Central New Jersey", auction: "iaai", state: "NJ", city: "Central New Jersey", price: 1535 },
  { id: "iaai-NJ-Avenel New Jersey", auction: "iaai", state: "NJ", city: "Avenel New Jersey", price: 1535 },
  { id: "iaai-NJ-Sayreville", auction: "iaai", state: "NJ", city: "Sayreville", price: 1535 },
  { id: "iaai-NJ-Port Murray", auction: "iaai", state: "NJ", city: "Port Murray", price: 1565 },
  { id: "copart-AR-Fayetteville", auction: "copart", state: "AR", city: "Fayetteville", price: 2050 },
  { id: "iaai-AR-Fayetteville", auction: "iaai", state: "AR", city: "Fayetteville", price: 2020 },
  { id: "copart-AR-Little rock", auction: "copart", state: "AR", city: "Little rock", price: 2020 },
  { id: "iaai-AR-Little rock", auction: "iaai", state: "AR", city: "Little rock", price: 2050 },
  { id: "copart-NE-Lincoln", auction: "copart", state: "NE", city: "Lincoln", price: 2060 },
  { id: "iaai-NE-Omaha", auction: "iaai", state: "NE", city: "Omaha", price: 2035 },
  { id: "iaai-NE-Omaha South", auction: "iaai", state: "NE", city: "Omaha South", price: 2035 },
  { id: "copart-WY-Casper", auction: "copart", state: "WY", city: "Casper", price: 2635 },
  { id: "iaai-WY-Casper", auction: "iaai", state: "WY", city: "Casper", price: 2805 },
  { id: "copart-GA-Macon", auction: "copart", state: "GA", city: "Macon", price: 1765 },
  { id: "iaai-GA-Macon", auction: "iaai", state: "GA", city: "Macon", price: 1635 },
  { id: "copart-GA-Cartersville", auction: "copart", state: "GA", city: "Cartersville", price: 1665 },
  { id: "copart-GA-Tifton", auction: "copart", state: "GA", city: "Tifton", price: 1705 },
  { id: "iaai-GA-Tifton", auction: "iaai", state: "GA", city: "Tifton", price: 1645 },
  { id: "copart-GA-Savannah", auction: "copart", state: "GA", city: "Savannah", price: 1625 },
  { id: "iaai-GA-Savannah", auction: "iaai", state: "GA", city: "Savannah", price: 1485 },
  { id: "copart-GA-Atalanta East", auction: "copart", state: "GA", city: "Atalanta East", price: 1685 },
  { id: "iaai-GA-Atalanta East", auction: "iaai", state: "GA", city: "Atalanta East", price: 1685 },
  { id: "iaai-GA-Atalanta North", auction: "iaai", state: "GA", city: "Atalanta North", price: 1685 },
  { id: "iaai-GA-Atalanta South", auction: "iaai", state: "GA", city: "Atalanta South", price: 1685 },
  { id: "copart-GA-Atalanta West", auction: "copart", state: "GA", city: "Atalanta West", price: 1685 },
  { id: "iaai-GA-Atalanta West", auction: "iaai", state: "GA", city: "Atalanta West", price: 1685 },
  { id: "copart-GA-Augusta", auction: "copart", state: "GA", city: "Augusta", price: 1685 },
  { id: "iaai-GA-Atalanta", auction: "iaai", state: "GA", city: "Atalanta", price: 1685 },
  { id: "copart-GA-Lake City", auction: "copart", state: "GA", city: "Lake City", price: 1685 },
  { id: "copart-SD-Rapid City", auction: "copart", state: "SD", city: "Rapid City", price: 2585 },
  { id: "iaai-SD-Sioux Falls", auction: "iaai", state: "SD", city: "Sioux Falls", price: 1335 },
  { id: "copart-MA-West Warren", auction: "copart", state: "MA", city: "West Warren", price: 1685 },
  { id: "copart-MA-North Boston", auction: "copart", state: "MA", city: "North Boston", price: 1685 },
  { id: "copart-MA-South Boston", auction: "copart", state: "MA", city: "South Boston", price: 1685 },
  { id: "iaai-MA-Templeton", auction: "iaai", state: "MA", city: "Templeton", price: 1735 },
  { id: "iaai-MA-Boston - Shirley", auction: "iaai", state: "MA", city: "Boston - Shirley", price: 1685 },
  { id: "iaai-MA-Tounton", auction: "iaai", state: "MA", city: "Tounton", price: 1715 },
  { id: "copart-VT-Rutland", auction: "copart", state: "VT", city: "Rutland", price: 1885 },
  { id: "iaai-VT-Burlington", auction: "iaai", state: "VT", city: "Burlington", price: 1885 },
  { id: "copart-CA-Antelope", auction: "copart", state: "CA", city: "Antelope", price: 2410 },
  { id: "copart-CA-Long Beach", auction: "copart", state: "CA", city: "Long Beach", price: 2185 },
  { id: "copart-CA-Sun Valley", auction: "copart", state: "CA", city: "Sun Valley", price: 2185 },
  { id: "copart-CA-Van Nuys", auction: "copart", state: "CA", city: "Van Nuys", price: 2235 },
  { id: "copart-CA-Vallejo", auction: "copart", state: "CA", city: "Vallejo", price: 2360 },
  { id: "copart-CA-San Jose", auction: "copart", state: "CA", city: "San Jose", price: 2360 },
  { id: "copart-CA-San Diego", auction: "copart", state: "CA", city: "San Diego", price: 2325 },
  { id: "copart-CA-Sacramento", auction: "copart", state: "CA", city: "Sacramento", price: 2385 },
  { id: "iaai-CA-Sacramento", auction: "iaai", state: "CA", city: "Sacramento", price: 2360 },
  { id: "copart-CA-Rancho Cucamonga", auction: "copart", state: "CA", city: "Rancho Cucamonga", price: 2245 },
  { id: "copart-CA-Martinez", auction: "copart", state: "CA", city: "Martinez", price: 2360 },
  { id: "copart-CA-Los Angeles", auction: "copart", state: "CA", city: "Los Angeles", price: 2235 },
  { id: "copart-CA-Hayward", auction: "copart", state: "CA", city: "Hayward", price: 2385 },
  { id: "copart-CA-Frenso", auction: "copart", state: "CA", city: "Frenso", price: 2335 },
  { id: "iaai-CA-Frenso", auction: "iaai", state: "CA", city: "Frenso", price: 2335 },
  { id: "copart-CA-San Bernardino", auction: "copart", state: "CA", city: "San Bernardino", price: 2205 },
  { id: "copart-CA-Bakersfield", auction: "copart", state: "CA", city: "Bakersfield", price: 2260 },
  { id: "copart-CA-Redding", auction: "copart", state: "CA", city: "Redding", price: 2520 },
  { id: "copart-CA-Adelanto", auction: "copart", state: "CA", city: "Adelanto", price: 2195 },
  { id: "copart-CA-Mentone", auction: "copart", state: "CA", city: "Mentone", price: 2235 },
  { id: "copart-CA-So Sacramento", auction: "copart", state: "CA", city: "So Sacramento", price: 2385 },
  { id: "copart-CA-Napa", auction: "copart", state: "CA", city: "Napa", price: 2455 },
  { id: "iaai-CA-ACE Carson", auction: "iaai", state: "CA", city: "ACE Carson", price: 2225 },
  { id: "iaai-CA-ACE Perris", auction: "iaai", state: "CA", city: "ACE Perris", price: 2295 },
  { id: "iaai-CA-San Diego", auction: "iaai", state: "CA", city: "San Diego", price: 2325 },
  { id: "iaai-CA-North Hollywood", auction: "iaai", state: "CA", city: "North Hollywood", price: 2225 },
  { id: "iaai-CA-High Desert", auction: "iaai", state: "CA", city: "High Desert", price: 2285 },
  { id: "iaai-CA-Los Angeles", auction: "iaai", state: "CA", city: "Los Angeles", price: 2225 },
  { id: "iaai-CA-Fremont", auction: "iaai", state: "CA", city: "Fremont", price: 2360 },
  { id: "iaai-CA-Fontana", auction: "iaai", state: "CA", city: "Fontana", price: 2205 },
  { id: "iaai-CA-Colton", auction: "iaai", state: "CA", city: "Colton", price: 2195 },
  { id: "iaai-CA-East Bay", auction: "iaai", state: "CA", city: "East Bay", price: 2360 },
  { id: "iaai-CA-Anaheim", auction: "iaai", state: "CA", city: "Anaheim", price: 2185 },
  { id: "iaai-CA-Los Angeles South", auction: "iaai", state: "CA", city: "Los Angeles South", price: 2225 },
  { id: "iaai-ACE-Perris 2", auction: "iaai", state: "ACE", city: "Perris 2", price: 2295 },
  { id: "iaai-CA-Santa Clarita", auction: "iaai", state: "CA", city: "Santa Clarita", price: 2235 },
  { id: "iaai-CA-Riverside", auction: "iaai", state: "CA", city: "Riverside", price: 2215 },
  { id: "iaai-CA-Stockton", auction: "iaai", state: "CA", city: "Stockton", price: 2485 },
  { id: "copart-KS-Wichita", auction: "copart", state: "KS", city: "Wichita", price: 2105 },
  { id: "iaai-KS-Wichita", auction: "iaai", state: "KS", city: "Wichita", price: 2085 },
  { id: "copart-KS-Kansas City", auction: "copart", state: "KS", city: "Kansas City", price: 2135 },
  { id: "iaai-KS-Kansas City", auction: "iaai", state: "KS", city: "Kansas City", price: 2135 },
  { id: "copart-TN-Memphis", auction: "copart", state: "TN", city: "Memphis", price: 1975 },
  { id: "iaai-TN-Memphis", auction: "iaai", state: "TN", city: "Memphis", price: 1835 },
  { id: "copart-TN-Knoxville", auction: "copart", state: "TN", city: "Knoxville", price: 1935 },
  { id: "iaai-TN-Knoxville", auction: "iaai", state: "TN", city: "Knoxville", price: 1735 },
  { id: "copart-TN-Nashville", auction: "copart", state: "TN", city: "Nashville", price: 1935 },
  { id: "iaai-TN-Nashville", auction: "iaai", state: "TN", city: "Nashville", price: 1780 },
  { id: "iaai-TN-Chattanooga", auction: "iaai", state: "TN", city: "Chattanooga", price: 1735 },
  { id: "copart-MI-Detroit", auction: "copart", state: "MI", city: "Detroit", price: 1935 },
  { id: "iaai-MI-Detroit", auction: "iaai", state: "MI", city: "Detroit", price: 1935 },
  { id: "copart-MI-Ionia", auction: "copart", state: "MI", city: "Ionia", price: 1985 },
  { id: "copart-MI-Lansing", auction: "copart", state: "MI", city: "Lansing", price: 1935 },
  { id: "copart-MI-Flint", auction: "copart", state: "MI", city: "Flint", price: 1935 },
  { id: "iaai-MI-Flint", auction: "iaai", state: "MI", city: "Flint", price: 1935 },
  { id: "iaai-MI-Grand Rapids", auction: "iaai", state: "MI", city: "Grand Rapids", price: 1985 },
  { id: "copart-OK-Tusla", auction: "copart", state: "OK", city: "Tusla", price: 1985 },
  { id: "iaai-OK-Tusla", auction: "iaai", state: "OK", city: "Tusla", price: 1985 },
  { id: "copart-OK-Oklahoma city", auction: "copart", state: "OK", city: "Oklahoma city", price: 1985 },
  { id: "iaai-OK-Oklahoma city", auction: "iaai", state: "OK", city: "Oklahoma city", price: 1985 },
  { id: "copart-AK-Anchorage", auction: "copart", state: "AK", city: "Anchorage", price: 5285 },
  { id: "iaai-AK-Anchorage", auction: "iaai", state: "AK", city: "Anchorage", price: 4985 },
  { id: "copart-AK-Anchorage South", auction: "copart", state: "AK", city: "Anchorage South", price: 5285 },
  { id: "copart-RI-Exeter", auction: "copart", state: "RI", city: "Exeter", price: 1710 },
  { id: "iaai-RI-Providence", auction: "iaai", state: "RI", city: "Providence", price: 1710 },
  { id: "copart-ME-Lyman", auction: "copart", state: "ME", city: "Lyman", price: 1835 },
  { id: "copart-ME-Windham", auction: "copart", state: "ME", city: "Windham", price: 1935 },
  { id: "iaai-ME-Portland Gorham", auction: "iaai", state: "ME", city: "Portland Gorham", price: 1845 },
  { id: "copart-IL-Wheeling", auction: "copart", state: "IL", city: "Wheeling", price: 1885 },
  { id: "copart-IL-Peoria", auction: "copart", state: "IL", city: "Peoria", price: 1915 },
  { id: "copart-IL-Chicago North", auction: "copart", state: "IL", city: "Chicago North", price: 1885 },
  { id: "iaai-IL-Chicago North", auction: "iaai", state: "IL", city: "Chicago North", price: 1935 },
  { id: "copart-IL-Chicago South", auction: "copart", state: "IL", city: "Chicago South", price: 1885 },
  { id: "iaai-IL-Chicago South", auction: "iaai", state: "IL", city: "Chicago South", price: 1935 },
  { id: "copart-IL-Sourthen Illinois", auction: "copart", state: "IL", city: "Sourthen Illinois", price: 1935 },
  { id: "iaai-IL-Speciality Division", auction: "iaai", state: "IL", city: "Speciality Division", price: 1905 },
  { id: "iaai-IL-Lincoln", auction: "iaai", state: "IL", city: "Lincoln", price: 2010 },
  { id: "copart-IL-Chicago West", auction: "copart", state: "IL", city: "Chicago West", price: 1885 },
  { id: "copart-IL-St.Louis", auction: "copart", state: "IL", city: "St.Louis", price: 1885 },
  { id: "copart-NC-Mocksville", auction: "copart", state: "NC", city: "Mocksville", price: 1665 },
  { id: "copart-NC-Lumberton", auction: "copart", state: "NC", city: "Lumberton", price: 1785 },
  { id: "copart-NC-Mebane", auction: "copart", state: "NC", city: "Mebane", price: 1695 },
  { id: "copart-NC-Raleigh", auction: "copart", state: "NC", city: "Raleigh", price: 1765 },
  { id: "iaai-NC-Raleigh", auction: "iaai", state: "NC", city: "Raleigh", price: 1880 },
  { id: "copart-NC-China Grove", auction: "copart", state: "NC", city: "China Grove", price: 1730 },
  { id: "copart-NC-Concord", auction: "copart", state: "NC", city: "Concord", price: 1635 },
  { id: "iaai-NC-Concord", auction: "iaai", state: "NC", city: "Concord", price: 1810 },
  { id: "copart-NC-Raleigh North", auction: "copart", state: "NC", city: "Raleigh North", price: 1785 },
  { id: "copart-NC-Gastonia", auction: "copart", state: "NC", city: "Gastonia", price: 1835 },
  { id: "copart-NC-Lagrange", auction: "copart", state: "NC", city: "Lagrange", price: 1835 },
  { id: "copart-NC-Greensboro", auction: "copart", state: "NC", city: "Greensboro", price: 1750 },
  { id: "copart-NC-Asheville", auction: "copart", state: "NC", city: "Asheville", price: 1750 },
  { id: "iaai-NC-Charlotte", auction: "iaai", state: "NC", city: "Charlotte", price: 1685 },
  { id: "iaai-NC-Wilmigton", auction: "iaai", state: "NC", city: "Wilmigton", price: 1715 },
  { id: "iaai-NC-High Point", auction: "iaai", state: "NC", city: "High Point", price: 1885 },
  { id: "copart-MO-Sikeston", auction: "copart", state: "MO", city: "Sikeston", price: 1935 },
  { id: "copart-MO-Springfield", auction: "copart", state: "MO", city: "Springfield", price: 1985 },
  { id: "iaai-MO-Springfield", auction: "iaai", state: "MO", city: "Springfield", price: 2335 },
  { id: "copart-MO-Columbia", auction: "copart", state: "MO", city: "Columbia", price: 1885 },
  { id: "copart-MO-St.Louis", auction: "copart", state: "MO", city: "St.Louis", price: 1985 },
  { id: "iaai-MO-Kansas City East", auction: "iaai", state: "MO", city: "Kansas City East", price: 1985 },
  { id: "copart-NV-Reno", auction: "copart", state: "NV", city: "Reno", price: 2535 },
  { id: "iaai-NV-Reno", auction: "iaai", state: "NV", city: "Reno", price: 2535 },
  { id: "copart-NV-Las Vegas", auction: "copart", state: "NV", city: "Las Vegas", price: 2355 },
  { id: "iaai-NV-Las Vegas", auction: "iaai", state: "NV", city: "Las Vegas", price: 2355 },
  { id: "copart-NV-Las Vegas West", auction: "copart", state: "NV", city: "Las Vegas West", price: 2435 },
  { id: "copart-HI-Honolulu", auction: "copart", state: "HI", city: "Honolulu", price: 4465 },
  { id: "iaai-HI-Honolulu", auction: "iaai", state: "HI", city: "Honolulu", price: 4465 },
  { id: "copart-SC-North Charleston", auction: "copart", state: "SC", city: "North Charleston", price: 1595 },
  { id: "copart-SC-Spartanburg", auction: "copart", state: "SC", city: "Spartanburg", price: 1835 },
  { id: "copart-SC-Columbia", auction: "copart", state: "SC", city: "Columbia", price: 1825 },
  { id: "iaai-SC-Lexington", auction: "iaai", state: "SC", city: "Lexington", price: 1765 },
  { id: "iaai-SC-Greenville", auction: "iaai", state: "SC", city: "Greenville", price: 1685 },
  { id: "iaai-SC-Charleston", auction: "iaai", state: "SC", city: "Charleston", price: 1485 },
  { id: "copart-MD-DC-Washington DC", auction: "copart", state: "MD", city: "DC-Washington DC", price: 1660 },
  { id: "iaai-MD-DC-Washington DC", auction: "iaai", state: "MD", city: "DC-Washington DC", price: 1660 },
  { id: "copart-MD-Baltimore", auction: "copart", state: "MD", city: "Baltimore", price: 1660 },
  { id: "iaai-MD-Baltimore", auction: "iaai", state: "MD", city: "Baltimore", price: 1660 },
  { id: "copart-MD-Baltimore East", auction: "copart", state: "MD", city: "Baltimore East", price: 1710 },
  { id: "copart-MD-Dundalk", auction: "copart", state: "MD", city: "Dundalk", price: 1660 },
  { id: "iaai-MD-Elkton", auction: "iaai", state: "MD", city: "Elkton", price: 1735 },
  { id: "copart-IN-Indianapolis", auction: "copart", state: "IN", city: "Indianapolis", price: 1910 },
  { id: "iaai-IN-Indianapolis", auction: "iaai", state: "IN", city: "Indianapolis", price: 1935 },
  { id: "copart-IN-Fort Wayne", auction: "copart", state: "IN", city: "Fort Wayne", price: 1885 },
  { id: "iaai-IN-Fort Wayne", auction: "iaai", state: "IN", city: "Fort Wayne", price: 1935 },
  { id: "copart-IN-Cicero", auction: "copart", state: "IN", city: "Cicero", price: 1985 },
  { id: "copart-IN-Dyer", auction: "copart", state: "IN", city: "Dyer", price: 1935 },
  { id: "copart-IN-South Bend", auction: "copart", state: "IN", city: "South Bend", price: 1985 },
  { id: "iaai-IN-Indianapolis South", auction: "iaai", state: "IN", city: "Indianapolis South", price: 1985 },
  { id: "copart-ND-Bismarck", auction: "copart", state: "ND", city: "Bismarck", price: 2535 },
  { id: "iaai-ND-Fargo", auction: "iaai", state: "ND", city: "Fargo", price: 2535 },
  { id: "copart-WV-Charleston", auction: "copart", state: "WV", city: "Charleston", price: 1885 },
  { id: "iaai-WV-Shady Spring", auction: "iaai", state: "WV", city: "Shady Spring", price: 1910 },
  { id: "iaai-WV-Buckhannon", auction: "iaai", state: "WV", city: "Buckhannon", price: 1905 },
  { id: "copart-DE-Seaford", auction: "copart", state: "DE", city: "Seaford", price: 1710 },
  { id: "iaai-DE-New Castle", auction: "iaai", state: "DE", city: "New Castle", price: 1635 },
  { id: "copart-OR-Portland South", auction: "copart", state: "OR", city: "Portland South", price: 2710 },
  { id: "iaai-OR-Portland South", auction: "iaai", state: "OR", city: "Portland South", price: 2715 },
  { id: "copart-OR-Portland North", auction: "copart", state: "OR", city: "Portland North", price: 2710 },
  { id: "copart-OR-Eugene", auction: "copart", state: "OR", city: "Eugene", price: 2660 },
  { id: "iaai-OR-Eugene", auction: "iaai", state: "OR", city: "Eugene", price: 2660 },
  { id: "iaai-OR-Portland West", auction: "iaai", state: "OR", city: "Portland West", price: 2710 },
  { id: "iaai-OR-Portland", auction: "iaai", state: "OR", city: "Portland", price: 2685 },
  { id: "copart-KY-Lexington West", auction: "copart", state: "KY", city: "Lexington West", price: 1935 },
  { id: "copart-KY-Walton", auction: "copart", state: "KY", city: "Walton", price: 2035 },
  { id: "copart-KY-Louisville", auction: "copart", state: "KY", city: "Louisville", price: 2075 },
  { id: "copart-KY-Lexington East", auction: "copart", state: "KY", city: "Lexington East", price: 2035 },
  { id: "copart-KY-Earlington", auction: "copart", state: "KY", city: "Earlington", price: 2075 },
  { id: "copart-KY-Paducah", auction: "copart", state: "KY", city: "Paducah", price: 1935 },
  { id: "copart-KY-Bowling Green", auction: "copart", state: "KY", city: "Bowling Green", price: 1935 },
  { id: "copart-KY-Ashland", auction: "copart", state: "KY", city: "Ashland", price: 1935 },
  { id: "copart-KY-Louisville North", auction: "copart", state: "KY", city: "Louisville North", price: 1935 },
];

export async function POST(req: NextRequest) {
  const authHeader = req.headers.get("Authorization");
  if (!authHeader) {
    return NextResponse.json({ error: "Missing Authorization header" }, { status: 401 });
  }

  const rows = tariffs.map((t) => ({
    id: t.id,
    auction: t.auction,
    state: t.state,
    city: t.city,
    yard_name: t.city,
    port: t.city,
    inland_price: t.price,
    ocean_price: 0,
    active: true,
  }));

  const headers = {
    apikey: anonKey,
    Authorization: authHeader,
    "Content-Type": "application/json",
  };

  const deactivateRes = await fetch(
    `${supabaseUrl}/rest/v1/location_tariffs?id=not.is.null`,
    {
      method: "PATCH",
      headers: { ...headers, Prefer: "return=minimal" },
      body: JSON.stringify({ active: false }),
    },
  );

  if (!deactivateRes.ok) {
    const text = await deactivateRes.text();
    return NextResponse.json(
      { error: `Failed to deactivate existing tariffs: ${deactivateRes.status} - ${text}` },
      { status: 500 },
    );
  }

  const batchSize = 50;
  let inserted = 0;
  const errors: string[] = [];

  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const res = await fetch(`${supabaseUrl}/rest/v1/location_tariffs`, {
      method: "POST",
      headers: {
        ...headers,
        Prefer: "resolution=merge-duplicates",
      },
      body: JSON.stringify(batch),
    });

    if (res.ok) {
      inserted += batch.length;
    } else {
      const text = await res.text();
      errors.push(`Batch ${i / batchSize + 1}: ${res.status} - ${text}`);
    }
  }

  return NextResponse.json({
    total: rows.length,
    inserted,
    deactivatedExisting: true,
    errors,
  });
}
